version: "3.9" # optional since v1.27.0
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./client:/app"
      - "/app/node_modules"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./server:/app"
      - "/app/node_modules"

volumes:
  logvolume01: {}
